{% set name = "mmh3" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hajimes/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 5ac08a79c9f6ba64062d7203fcc918326dbbe7fa7c9a538d1849bafd861430e5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools

  run:
    - python

test:
  imports:
    - mmh3

about:
  home: http://packages.python.org/mmh3
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.

extra:
  recipe-maintainers:
    - johnlees
