{% set name = "mmh3" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hajimes/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 6636b19c4d7e2a18a838426d31d8f924cbab308ffcc6a0b66824c1bf0b405a79

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - mmh3

about:
  home: http://packages.python.org/mmh3
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.

extra:
  recipe-maintainers:
    - johnlees
