{% set name = "mmh3" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hajimes/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 1ed083c77d7692afb2825618337541bcde837fdc0a42cc67f73c7240469a20f8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip

  run:
    - python
    - numpy

test:
  imports:
    - mmh3

about:
  home: http://packages.python.org/mmh3
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.

extra:
  recipe-maintainers:
    - johnlees
